"""modelos listos

Revision ID: fc3353db433a
Revises: 
Create Date: 2025-02-24 17:02:27.771682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3353db433a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.String(length=40), nullable=True),
    sa.Column('apellidos', sa.String(length=40), nullable=True),
    sa.Column('tipo_de_documento', sa.Enum('CC', 'TI', 'CE', name='tiposdedocumento'), nullable=True),
    sa.Column('numero_documento', sa.String(length=11), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('empresa', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_cita', sa.Enum('General', 'Especialista', name='tipo_cita_enum'), nullable=False),
    sa.Column('nombre_medico', sa.String(length=100), nullable=False),
    sa.Column('direccion_cita', sa.String(length=255), nullable=False),
    sa.Column('fecha_cita', sa.Date(), nullable=False),
    sa.Column('hora_cita', sa.Time(), nullable=False),
    sa.Column('asistencia', sa.Enum('Si', 'No', name='asistencia_enum'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
